name: liveness_verify_flutter
description: Guided Flutter face-liveness verification with active challenges and server-side anti-spoofing for lightweight on-device operation.
version: 0.1.1
repository: https://github.com/nicolafeby/research-liveness/tree/main/packages/liveness_verify_flutter
issue_tracker: https://github.com/nicolafeby/research-liveness/issues

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.12.0+2
  dio: ^5.10.0
  flutter_bloc: ^9.1.1
  image: ^4.10.1
  json_annotation: ^4.12.0

dev_dependencies:
  build_runner: ^2.15.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.14.0

flutter:
  uses-material-design: true
